const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.sliderbar,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Acts.SetBlur,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Particles.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.sliderbar.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.sliderbar.Acts.SetMaximum,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Button.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{MultiplierButton: 0},
	{MultiplyerText: 0},
	{BackButton: 0},
	{DebtFreeWarning: 0},
	{BallDropper: 0},
	{BallSpawn: 0},
	{CurrentBalls: 0},
	{GoldenBallSpawnRate: 0},
	{CurrentSpanwRate: 0},
	{GoldenBallMulti: 0},
	{CurrentGBallMulti: 0},
	{PurchaseGball: 0},
	{LoanAmount: 0},
	{InterestMultiplier: 0},
	{Loanbutton: 0},
	{InterestText: 0},
	{Physics: 0},
	{bumper: 0},
	{align: 0},
	{Fade: 0},
	{ball: 0},
	{PrizeMultiplyer: 0},
	{Prize: 0},
	{Mouse: 0},
	{CanMove: 0},
	{Spawner: 0},
	{amount: 0},
	{moneytext: 0},
	{moneyperballtext: 0},
	{TiledBackground: 0},
	{NoCodeText: 0},
	{PricePerBall: 0},
	{NumberOfBalls: 0},
	{NumberOfBallsText: 0},
	{Spawn: 0},
	{Price: 0},
	{MaxPrice: 0},
	{ShopOpen: 0},
	{bigwin: 0},
	{"50xHitbox": 0},
	{MaxBalls: 0},
	{HalfPrice: 0},
	{RightClickToLock: 0},
	{Reset: 0},
	{MultiCost: 0},
	{Timer: 0},
	{Profit: 0},
	{SellOrgans: 0},
	{Dying: 0},
	{PayDebt: 0},
	{restart: 0},
	{Browser: 0},
	{moneyperball: 0},
	{money: 0},
	{moneyThatRound: 0},
	{InterestAmount: 0},
	{BallsFalling: 0},
	{PurchacedMove: 0},
	{PricePerBallSave: 0},
	{NumberOfBallsSave: 0},
	{SecondsToReset: 0},
	{FinalChange: 0},
	{OddsOfGBall: 0},
	{IsDying: 0},
	{TimeLeft: 0},
	{GBallPurchaced: 0},
	{Multiplier: 0},
	{MultiplierCost: 0},
	{BallsCost: 0},
	{AddedBalls: 0},
	{GBallSpawnRatePrice: 0},
	{GBallSpawnRate: 0},
	{GBallMultiPrice: 0},
	{GBallMulti: 0}
];

self.InstanceType = {
	MultiplierButton: class extends self.IButtonInstance {},
	MultiplyerText: class extends self.ITextInstance {},
	BackButton: class extends self.IButtonInstance {},
	DebtFreeWarning: class extends self.ITextInstance {},
	BallDropper: class extends self.IButtonInstance {},
	BallSpawn: class extends self.IButtonInstance {},
	CurrentBalls: class extends self.ITextInstance {},
	GoldenBallSpawnRate: class extends self.IButtonInstance {},
	CurrentSpanwRate: class extends self.ITextInstance {},
	GoldenBallMulti: class extends self.IButtonInstance {},
	CurrentGBallMulti: class extends self.ITextInstance {},
	PurchaseGball: class extends self.IButtonInstance {},
	Loanbutton: class extends self.IButtonInstance {},
	InterestText: class extends self.ITextInstance {},
	bumper: class extends self.ISpriteInstance {},
	align: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Prize: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Spawner: class extends self.ISpriteInstance {},
	amount: class extends self.ITextInstance {},
	moneytext: class extends self.ITextInstance {},
	moneyperballtext: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	NoCodeText: class extends self.ITextInstance {},
	PricePerBall: class extends self.ISliderBarInstance {},
	NumberOfBalls: class extends self.ISliderBarInstance {},
	NumberOfBallsText: class extends self.ITextInstance {},
	Spawn: class extends self.IButtonInstance {},
	Price: class extends self.ITextInstance {},
	MaxPrice: class extends self.IButtonInstance {},
	ShopOpen: class extends self.IButtonInstance {},
	bigwin: class extends self.IParticlesInstance {},
	_50xHitbox: class extends self.ISpriteInstance {},
	MaxBalls: class extends self.IButtonInstance {},
	HalfPrice: class extends self.IButtonInstance {},
	RightClickToLock: class extends self.ITextInstance {},
	Reset: class extends self.IButtonInstance {},
	MultiCost: class extends self.ITextInstance {},
	Timer: class extends self.ITextInstance {},
	Profit: class extends self.ITextInstance {},
	SellOrgans: class extends self.IButtonInstance {},
	Dying: class extends self.ITextInstance {},
	PayDebt: class extends self.IButtonInstance {},
	restart: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {}
}