const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Massive_Cube_Rex_CSV2Array,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.RotateCounterclockwise,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.SetStopOnSolids,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Behaviors.Physics.Acts.SetAwake,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.Massive_Cube_Rex_CSV2Array.Acts.CSV2Array,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.IsEnabled,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Cnds.HasTags,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Particles.Cnds.IsOnScreen,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.SetY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Button.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{MoveTo: 0},
	{Physics: 0},
	{trollGround: 0},
	{trollGround2: 0},
	{trollGround3: 0},
	{trollGround4: 0},
	{trollGround5: 0},
	{trollGround6: 0},
	{trollGround7: 0},
	{trollGround8: 0},
	{trollGround9: 0},
	{Sine: 0},
	{trollLava: 0},
	{trollLava2: 0},
	{trollLava3: 0},
	{trollLava4: 0},
	{trollLava5: 0},
	{trollLava6: 0},
	{trollLava7: 0},
	{trollLava8: 0},
	{trollLava9: 0},
	{hitbox1: 0},
	{hitbox2: 0},
	{hitbox3: 0},
	{hitbox4: 0},
	{hitbox5: 0},
	{hitbox6: 0},
	{hitbox7: 0},
	{hitbox8: 0},
	{hitbox9: 0},
	{isDeadly: 0},
	{hitGround: 0},
	{twamp: 0},
	{twamp2: 0},
	{twamp3: 0},
	{twamp4: 0},
	{twamp5: 0},
	{twamp6: 0},
	{twamp7: 0},
	{twamp8: 0},
	{twamp9: 0},
	{breakaway: 0},
	{PhysicsText: 0},
	{PhysicsText2: 0},
	{movingGround: 0},
	{movingGround2: 0},
	{movingGround3: 0},
	{movingGround4: 0},
	{movingGround5: 0},
	{movingGround6: 0},
	{movingGround7: 0},
	{movingGround8: 0},
	{movingGround9: 0},
	{AJAX: 0},
	{Send: 0},
	{Score: 0},
	{NoCodeText: 0},
	{Name2: 0},
	{Name: 0},
	{Leaderboard2: 0},
	{FormText: 0},
	{Difficulty: 0},
	{Background: 0},
	{Array: 0},
	{Pin: 0},
	{deathParticles: 0},
	{ChangeSpeed: 0},
	{death: 0},
	{fallingBlock: 0},
	{BreakableSurface: 0},
	{Piece: 0},
	{ground: 0},
	{hasLegs: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{player: 0},
	{Keyboard: 0},
	{Particles: 0},
	{Particles2: 0},
	{object: 0},
	{welcome: 0},
	{willWork: 0},
	{nextLevel: 0},
	{invisGround: 0},
	{Rotate: 0},
	{lava: 0},
	{falloutOfWorld: 0},
	{Sprite: 0},
	{nodielava: 0},
	{distanceMarker: 0},
	{twampParticle: 0},
	{twampbreak: 0},
	{Fade: 0},
	{rollingBall: 0},
	{ZoomTarget: 0},
	{CameraHeight: 0},
	{zoomTrigger: 0},
	{Camera: 0},
	{NonChangableText: 0},
	{invistovis: 0},
	{secret: 0},
	{Activated: 0},
	{checkpoint: 0},
	{checkpointAura: 0},
	{Leaderboard: 0},
	{CSVToArray: 0},
	{Button1: 0},
	{movingLava: 0},
	{codeText: 0},
	{transition: 0},
	{fallingRock: 0},
	{winAura: 0},
	{TP: 0},
	{transition2: 0},
	{Credits: 0},
	{grayBackground: 0},
	{CreditsBG: 0},
	{Mouse: 0},
	{Timer: 0},
	{white: 0},
	{CurrentZoom: 0},
	{Target: 0},
	{Speed: 0},
	{gamefps: 0},
	{WillSpawn: 0},
	{MarbleGameStarted: 0},
	{CameraX: 0},
	{CameraY: 0},
	{TargetX: 0},
	{TargetY: 0},
	{CheckPointActivated: 0},
	{PlayerX: 0},
	{PlayerY: 0},
	{PlayerAcc: 0},
	{SheetCode: 0},
	{HasWon: 0},
	{HasSentAlready: 0},
	{S: 0},
	{WebAppURL: 0},
	{FirstTime: 0},
	{BossTimer: 0},
	{BossSpeedrun: 0},
	{LevelSelected: 0},
	{SheetCode2: 0},
	{HasWonBoss: 0},
	{HasSentAlreadyBoss: 0}
];

self.InstanceType = {
	trollGround: class extends self.ISpriteInstance {},
	trollGround2: class extends self.ISpriteInstance {},
	trollGround3: class extends self.ISpriteInstance {},
	trollGround4: class extends self.ISpriteInstance {},
	trollGround5: class extends self.ISpriteInstance {},
	trollGround6: class extends self.ISpriteInstance {},
	trollGround7: class extends self.ISpriteInstance {},
	trollGround8: class extends self.ISpriteInstance {},
	trollGround9: class extends self.ISpriteInstance {},
	trollLava: class extends self.ISpriteInstance {},
	trollLava2: class extends self.ISpriteInstance {},
	trollLava3: class extends self.ISpriteInstance {},
	trollLava4: class extends self.ISpriteInstance {},
	trollLava5: class extends self.ISpriteInstance {},
	trollLava6: class extends self.ISpriteInstance {},
	trollLava7: class extends self.ISpriteInstance {},
	trollLava8: class extends self.ISpriteInstance {},
	trollLava9: class extends self.ISpriteInstance {},
	hitbox1: class extends self.ISpriteInstance {},
	hitbox2: class extends self.ISpriteInstance {},
	hitbox3: class extends self.ISpriteInstance {},
	hitbox4: class extends self.ISpriteInstance {},
	hitbox5: class extends self.ISpriteInstance {},
	hitbox6: class extends self.ISpriteInstance {},
	hitbox7: class extends self.ISpriteInstance {},
	hitbox8: class extends self.ISpriteInstance {},
	hitbox9: class extends self.ISpriteInstance {},
	twamp: class extends self.ISpriteInstance {},
	twamp2: class extends self.ISpriteInstance {},
	twamp3: class extends self.ISpriteInstance {},
	twamp4: class extends self.ISpriteInstance {},
	twamp5: class extends self.ISpriteInstance {},
	twamp6: class extends self.ISpriteInstance {},
	twamp7: class extends self.ISpriteInstance {},
	twamp8: class extends self.ISpriteInstance {},
	twamp9: class extends self.ISpriteInstance {},
	breakaway: class extends self.ISpriteInstance {},
	PhysicsText: class extends self.ITextInstance {},
	PhysicsText2: class extends self.ITextInstance {},
	movingGround: class extends self.ISpriteInstance {},
	movingGround2: class extends self.ISpriteInstance {},
	movingGround3: class extends self.ISpriteInstance {},
	movingGround4: class extends self.ISpriteInstance {},
	movingGround5: class extends self.ISpriteInstance {},
	movingGround6: class extends self.ISpriteInstance {},
	movingGround7: class extends self.ISpriteInstance {},
	movingGround8: class extends self.ISpriteInstance {},
	movingGround9: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Send: class extends self.IButtonInstance {},
	Score: class extends self.ITextInstance {},
	NoCodeText: class extends self.ITextInstance {},
	Name2: class extends self.ITextInputInstance {},
	Name: class extends self.ITextInputInstance {},
	Leaderboard2: class extends self.ITextInstance {},
	FormText: class extends self.ITextInstance {},
	Difficulty: class extends self.ITextInputInstance {},
	Background: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	deathParticles: class extends self.IParticlesInstance {},
	death: class extends self.ISpriteInstance {},
	fallingBlock: class extends self.ISpriteInstance {},
	BreakableSurface: class extends self.ISpriteInstance {},
	Piece: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	object: class extends self.ISpriteInstance {},
	welcome: class extends self.ITextInstance {},
	nextLevel: class extends self.ISpriteInstance {},
	invisGround: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	falloutOfWorld: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	nodielava: class extends self.ISpriteInstance {},
	distanceMarker: class extends self.ISpriteInstance {},
	twampParticle: class extends self.IParticlesInstance {},
	twampbreak: class extends self.IParticlesInstance {},
	rollingBall: class extends self.ISpriteInstance {},
	zoomTrigger: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	NonChangableText: class extends self.ITextInstance {},
	invistovis: class extends self.ISpriteInstance {},
	secret: class extends self.ITextInputInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	checkpointAura: class extends self.IParticlesInstance {},
	Leaderboard: class extends self.ITextInstance {},
	CSVToArray: class extends self.IInstance {},
	Button1: class extends self.IButtonInstance {},
	movingLava: class extends self.ISpriteInstance {},
	codeText: class extends self.ITextInstance {},
	transition: class extends self.ISpriteInstance {},
	fallingRock: class extends self.ISpriteInstance {},
	winAura: class extends self.IParticlesInstance {},
	TP: class extends self.IParticlesInstance {},
	transition2: class extends self.ISpriteInstance {},
	Credits: class extends self.ITextInstance {},
	grayBackground: class extends self.ITiledBackgroundInstance {},
	CreditsBG: class extends self.IParticlesInstance {},
	Mouse: class extends self.IInstance {},
	Timer: class extends self.ITextInstance {},
	white: class extends self.ISpriteInstance {}
}